# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directory: "/build/plugins/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gomod"
    directory: "/protoc-gen-builder/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gomod"
    directory: "/protoc-gen-cgo/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gomod"
    directory: "/protoc-gen-choice/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_mho_go/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_kpm_v2/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_kpm_v2_go/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_mho/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_ni/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_rc_pre/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_rsm/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_kpm/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_rc_pre_go/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/e2sm_rc/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "gomod"
    directory: "/test_sm_aper_go_lib/"
    schedule:
      interval: "weekly"