linters:
  enable:
    - gofmt
#    - revive
    - misspell
    - typecheck
    - errcheck
    - dogsled
    - unconvert
    - nakedret
    - exportloopref
run:
  skip-dirs:
    - modelplugin
#issues:
#  exclude-rules:
#    - path: pkg/southbound/e2ap/asn1cgo/TriggeringMessage.go
#      linters:
#        - misspell