/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxofMessageProtocolTests_RCPRE (15)
#define maxofRICstyles_RCPRE (63)
#define maxPLMN_RCPRE (12)
#define maxNR_RCPRE (4096)
#define maxEARFCN_RCPRE (262143)
#define maxNRARFCN_RCPRE (3279167)
#define maxPCI_RCPRE (1007)
#define maxPciRange_RCPRE (100)
#define maxofRANparameters_RCPRE (65535)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
