/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-PRE-IEs"
 * 	found in "../v2/e2sm-rc-pre_v2_rsys.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_CellGlobalID_RCPRE_H_
#define	_CellGlobalID_RCPRE_H_


#include "asn_application.h"

/* Including external dependencies */
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum CellGlobalID_RCPRE_PR {
	CellGlobalID_RCPRE_PR_NOTHING,	/* No components present */
	CellGlobalID_RCPRE_PR_nr_CGI,
	CellGlobalID_RCPRE_PR_eUTRA_CGI
	/* Extensions may appear below */
	
} CellGlobalID_RCPRE_PR;

/* Forward declarations */
struct NRCGI_RCPRE;
struct EUTRACGI_RCPRE;

/* CellGlobalID-RCPRE */
typedef struct CellGlobalID_RCPRE {
	CellGlobalID_RCPRE_PR present;
	union CellGlobalID_RCPRE_u {
		struct NRCGI_RCPRE	*nr_CGI;
		struct EUTRACGI_RCPRE	*eUTRA_CGI;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} CellGlobalID_RCPRE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_CellGlobalID_RCPRE;
extern asn_CHOICE_specifics_t asn_SPC_CellGlobalID_RCPRE_specs_1;
extern asn_TYPE_member_t asn_MBR_CellGlobalID_RCPRE_1[2];
extern asn_per_constraints_t asn_PER_type_CellGlobalID_RCPRE_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _CellGlobalID_RCPRE_H_ */
#include "asn_internal.h"
