/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-PRE-IEs"
 * 	found in "../v2/e2sm-rc-pre_v2_rsys.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_E2SM_RC_PRE_ControlHeader_Format1_RCPRE_H_
#define	_E2SM_RC_PRE_ControlHeader_Format1_RCPRE_H_


#include "asn_application.h"

/* Including external dependencies */
#include "RC-PRE-Command-RCPRE.h"
#include "RIC-Control-Message-Priority-RCPRE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct CellGlobalID_RCPRE;

/* E2SM-RC-PRE-ControlHeader-Format1-RCPRE */
typedef struct E2SM_RC_PRE_ControlHeader_Format1_RCPRE {
	struct CellGlobalID_RCPRE	*cgi;	/* OPTIONAL */
	RC_PRE_Command_RCPRE_t	 rc_command;
	RIC_Control_Message_Priority_RCPRE_t	*ric_Control_Message_Priority;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_PRE_ControlHeader_Format1_RCPRE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RC_PRE_ControlHeader_Format1_RCPRE;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_PRE_ControlHeader_Format1_RCPRE_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_RC_PRE_ControlHeader_Format1_RCPRE_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RC_PRE_ControlHeader_Format1_RCPRE_H_ */
#include "asn_internal.h"
