/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-PRE-IEs"
 * 	found in "e2sm-rc-pre-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D e2sm_rc_pre_v01_asn1/asn1c-gen`
 */

#include "E2SM-RC-PRE-IndicationMessage-Format1.h"

#include "PCI-Range.h"
#include "NRT.h"
static int
memb_pci_Pool_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 100)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_neighbors_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 4096)) {
		/* Perform validation of the inner elements */
		return SEQUENCE_OF_constraint(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_pci_Pool_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 7,  7,  1,  100 }	/* (SIZE(1..100)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_neighbors_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 12,  12,  1,  4096 }	/* (SIZE(1..4096)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_pci_Pool_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 7,  7,  1,  100 }	/* (SIZE(1..100)) */,
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_neighbors_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 12,  12,  1,  4096 }	/* (SIZE(1..4096)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_pci_Pool_5[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_PCI_Range,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_pci_Pool_tags_5[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_pci_Pool_specs_5 = {
	sizeof(struct E2SM_RC_PRE_IndicationMessage_Format1__pci_Pool),
	offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1__pci_Pool, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_pci_Pool_5 = {
	"pci-Pool",
	"pci-Pool",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_pci_Pool_tags_5,
	sizeof(asn_DEF_pci_Pool_tags_5)
		/sizeof(asn_DEF_pci_Pool_tags_5[0]) - 1, /* 1 */
	asn_DEF_pci_Pool_tags_5,	/* Same as above */
	sizeof(asn_DEF_pci_Pool_tags_5)
		/sizeof(asn_DEF_pci_Pool_tags_5[0]), /* 2 */
	{ 0, &asn_PER_type_pci_Pool_constr_5, SEQUENCE_OF_constraint },
	asn_MBR_pci_Pool_5,
	1,	/* Single element */
	&asn_SPC_pci_Pool_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_neighbors_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_NRT,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_neighbors_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_neighbors_specs_8 = {
	sizeof(struct E2SM_RC_PRE_IndicationMessage_Format1__neighbors),
	offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1__neighbors, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_neighbors_8 = {
	"neighbors",
	"neighbors",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_neighbors_tags_8,
	sizeof(asn_DEF_neighbors_tags_8)
		/sizeof(asn_DEF_neighbors_tags_8[0]) - 1, /* 1 */
	asn_DEF_neighbors_tags_8,	/* Same as above */
	sizeof(asn_DEF_neighbors_tags_8)
		/sizeof(asn_DEF_neighbors_tags_8[0]), /* 2 */
	{ 0, &asn_PER_type_neighbors_constr_8, SEQUENCE_OF_constraint },
	asn_MBR_neighbors_8,
	1,	/* Single element */
	&asn_SPC_neighbors_specs_8	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2SM_RC_PRE_IndicationMessage_Format1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1, cgi),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_CellGlobalID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cgi"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1, dl_EARFCN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EARFCN,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"dl-EARFCN"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1, cell_Size),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Cell_Size,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"cell-Size"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1, pci_Pool),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_pci_Pool_5,
		0,
		{ 0, &asn_PER_memb_pci_Pool_constr_5,  memb_pci_Pool_constraint_1 },
		0, 0, /* No default value */
		"pci-Pool"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1, pci),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_PCI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"pci"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1, neighbors),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		0,
		&asn_DEF_neighbors_8,
		0,
		{ 0, &asn_PER_memb_neighbors_constr_8,  memb_neighbors_constraint_1 },
		0, 0, /* No default value */
		"neighbors"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_PRE_IndicationMessage_Format1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cgi */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* dl-EARFCN */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* cell-Size */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* pci-Pool */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* pci */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* neighbors */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_PRE_IndicationMessage_Format1_specs_1 = {
	sizeof(struct E2SM_RC_PRE_IndicationMessage_Format1),
	offsetof(struct E2SM_RC_PRE_IndicationMessage_Format1, _asn_ctx),
	asn_MAP_E2SM_RC_PRE_IndicationMessage_Format1_tag2el_1,
	6,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1 = {
	"E2SM-RC-PRE-IndicationMessage-Format1",
	"E2SM-RC-PRE-IndicationMessage-Format1",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1_tags_1,
	sizeof(asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RC_PRE_IndicationMessage_Format1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RC_PRE_IndicationMessage_Format1_1,
	6,	/* Elements count */
	&asn_SPC_E2SM_RC_PRE_IndicationMessage_Format1_specs_1	/* Additional specs */
};

