/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-PRE-IEs"
 * 	found in "e2sm-rc-pre-v1.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_EUTRACGI_H_
#define	_EUTRACGI_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PLMN-Identity.h"
#include "EUTRACellIdentity.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* EUTRACGI */
typedef struct EUTRACGI {
	PLMN_Identity_t	 pLMN_Identity;
	EUTRACellIdentity_t	 eUTRACellIdentity;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} EUTRACGI_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_EUTRACGI;
extern asn_SEQUENCE_specifics_t asn_SPC_EUTRACGI_specs_1;
extern asn_TYPE_member_t asn_MBR_EUTRACGI_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _EUTRACGI_H_ */
#include "asn_internal.h"
