/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-PRE-IEs"
 * 	found in "../v2/e2sm-rc-pre_v2_rsys.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_NRT_H_
#define	_NRT_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CellGlobalID.h"
#include "ARFCN.h"
#include "Cell-Size.h"
#include "PCI.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NRT */
typedef struct NRT {
	CellGlobalID_t	 cgi;
	ARFCN_t	 dl_ARFCN;
	Cell_Size_t	 cell_Size;
	PCI_t	 pci;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} NRT_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_NRT;
extern asn_SEQUENCE_specifics_t asn_SPC_NRT_specs_1;
extern asn_TYPE_member_t asn_MBR_NRT_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _NRT_H_ */
#include "asn_internal.h"
