/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_PRE_EventTriggerDefinition_RCPRE;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_PRE_IndicationHeader_RCPRE;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_PRE_IndicationMessage_RCPRE;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_PRE_ControlHeader_RCPRE;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_PRE_ControlMessage_RCPRE;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_PRE_ControlOutcome_RCPRE;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_PRE_RANfunction_Description_RCPRE;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module E2SM-RC-PRE-IEs in ../v2/e2sm-rc-pre_v2_rsys.asn */
	&asn_DEF_E2SM_RC_PRE_EventTriggerDefinition_RCPRE,	
	&asn_DEF_E2SM_RC_PRE_IndicationHeader_RCPRE,	
	&asn_DEF_E2SM_RC_PRE_IndicationMessage_RCPRE,	
	&asn_DEF_E2SM_RC_PRE_ControlHeader_RCPRE,	
	&asn_DEF_E2SM_RC_PRE_ControlMessage_RCPRE,	
	&asn_DEF_E2SM_RC_PRE_ControlOutcome_RCPRE,	
	&asn_DEF_E2SM_RC_PRE_RANfunction_Description_RCPRE,	
	0
};

