/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-PRE-IEs"
 * 	found in "../v2/e2sm-rc-pre_v2_rsys.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "RANparameterDef-Item-RCPRE.h"

asn_TYPE_member_t asn_MBR_RANparameterDef_Item_RCPRE_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANparameterDef_Item_RCPRE, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANparameter_ID_RCPRE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANparameterDef_Item_RCPRE, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANparameter_Name_RCPRE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANparameterDef_Item_RCPRE, ranParameter_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANparameter_Type_RCPRE,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Type"
		},
};
static const ber_tlv_tag_t asn_DEF_RANparameterDef_Item_RCPRE_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANparameterDef_Item_RCPRE_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ranParameter-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ranParameter-Type */
};
asn_SEQUENCE_specifics_t asn_SPC_RANparameterDef_Item_RCPRE_specs_1 = {
	sizeof(struct RANparameterDef_Item_RCPRE),
	offsetof(struct RANparameterDef_Item_RCPRE, _asn_ctx),
	asn_MAP_RANparameterDef_Item_RCPRE_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANparameterDef_Item_RCPRE = {
	"RANparameterDef-Item-RCPRE",
	"RANparameterDef-Item-RCPRE",
	&asn_OP_SEQUENCE,
	asn_DEF_RANparameterDef_Item_RCPRE_tags_1,
	sizeof(asn_DEF_RANparameterDef_Item_RCPRE_tags_1)
		/sizeof(asn_DEF_RANparameterDef_Item_RCPRE_tags_1[0]), /* 1 */
	asn_DEF_RANparameterDef_Item_RCPRE_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANparameterDef_Item_RCPRE_tags_1)
		/sizeof(asn_DEF_RANparameterDef_Item_RCPRE_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANparameterDef_Item_RCPRE_1,
	3,	/* Elements count */
	&asn_SPC_RANparameterDef_Item_RCPRE_specs_1	/* Additional specs */
};

