/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxInt16 (65535)
#define maxInt32 (4294967295)
#define maxInt64 (18446744073709551615U)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
