/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_Choice2_H_
#define	_Choice2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Choice2_PR {
	Choice2_PR_NOTHING,	/* No components present */
	Choice2_PR_choice2A,
	Choice2_PR_choice2B
} Choice2_PR;

/* Choice2 */
typedef struct Choice2 {
	Choice2_PR present;
	union Choice2_u {
		long	 choice2A;
		long	 choice2B;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Choice2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Choice2;
extern asn_CHOICE_specifics_t asn_SPC_Choice2_specs_1;
extern asn_TYPE_member_t asn_MBR_Choice2_1[2];
extern asn_per_constraints_t asn_PER_type_Choice2_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _Choice2_H_ */
#include "asn_internal.h"
