/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_ConstrainedChoice1_H_
#define	_ConstrainedChoice1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_CHOICE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ConstrainedChoice1_PR {
	ConstrainedChoice1_PR_NOTHING,	/* No components present */
	ConstrainedChoice1_PR_constrainedChoice1A
} ConstrainedChoice1_PR;

/* ConstrainedChoice1 */
typedef struct ConstrainedChoice1 {
	ConstrainedChoice1_PR present;
	union ConstrainedChoice1_u {
		long	 constrainedChoice1A;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} ConstrainedChoice1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_ConstrainedChoice1;
extern asn_CHOICE_specifics_t asn_SPC_ConstrainedChoice1_specs_1;
extern asn_TYPE_member_t asn_MBR_ConstrainedChoice1_1[1];
extern asn_per_constraints_t asn_PER_type_ConstrainedChoice1_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _ConstrainedChoice1_H_ */
#include "asn_internal.h"
