/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "ConstrainedChoice2.h"

static int
constrainedChoice2B_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 1 && value <= 4294967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_constrainedChoice2A_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_constrainedChoice2B_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 1 && value <= 4294967295)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_constrainedChoice2B_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  32, -1,  1,  4294967295 }	/* (1..4294967295,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_constrainedChoice2A_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  4,  4,  0,  15 }	/* (0..15,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_constrainedChoice2B_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  32, -1,  1,  4294967295 }	/* (1..4294967295,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_per_constraints_t asn_PER_type_ConstrainedChoice2_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_constrainedChoice2B_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_constrainedChoice2B_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_constrainedChoice2B_3 = {
	"constrainedChoice2B",
	"constrainedChoice2B",
	&asn_OP_NativeInteger,
	asn_DEF_constrainedChoice2B_tags_3,
	sizeof(asn_DEF_constrainedChoice2B_tags_3)
		/sizeof(asn_DEF_constrainedChoice2B_tags_3[0]) - 1, /* 1 */
	asn_DEF_constrainedChoice2B_tags_3,	/* Same as above */
	sizeof(asn_DEF_constrainedChoice2B_tags_3)
		/sizeof(asn_DEF_constrainedChoice2B_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_constrainedChoice2B_constr_3, constrainedChoice2B_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_constrainedChoice2B_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_ConstrainedChoice2_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct ConstrainedChoice2, choice.constrainedChoice2A),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_constrainedChoice2A_constr_2,  memb_constrainedChoice2A_constraint_1 },
		0, 0, /* No default value */
		"constrainedChoice2A"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct ConstrainedChoice2, choice.constrainedChoice2B),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_constrainedChoice2B_3,
		0,
		{ 0, &asn_PER_memb_constrainedChoice2B_constr_3,  memb_constrainedChoice2B_constraint_1 },
		0, 0, /* No default value */
		"constrainedChoice2B"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_ConstrainedChoice2_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* constrainedChoice2A */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* constrainedChoice2B */
};
asn_CHOICE_specifics_t asn_SPC_ConstrainedChoice2_specs_1 = {
	sizeof(struct ConstrainedChoice2),
	offsetof(struct ConstrainedChoice2, _asn_ctx),
	offsetof(struct ConstrainedChoice2, present),
	sizeof(((struct ConstrainedChoice2 *)0)->present),
	asn_MAP_ConstrainedChoice2_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_ConstrainedChoice2 = {
	"ConstrainedChoice2",
	"ConstrainedChoice2",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_ConstrainedChoice2_constr_1, CHOICE_constraint },
	asn_MBR_ConstrainedChoice2_1,
	2,	/* Elements count */
	&asn_SPC_ConstrainedChoice2_specs_1	/* Additional specs */
};

