/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_TEST_ConstrainedInt;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_UnconstrainedReal;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_Choices;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_ConstrainedChoices;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_PrintableString;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_List1;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_List2;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_ListExtensible1;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_ListExtensible2;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_List3;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_Enumerated;
extern struct asn_TYPE_descriptor_s asn_DEF_TEST_TopLevelPDU;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module TEST-SM-IEs in ../v1/test_sm.asn1 */
	&asn_DEF_TEST_ConstrainedInt,	
	&asn_DEF_TEST_UnconstrainedReal,	
	&asn_DEF_TEST_Choices,	
	&asn_DEF_TEST_ConstrainedChoices,	
	&asn_DEF_TEST_PrintableString,	
	&asn_DEF_TEST_List1,	
	&asn_DEF_TEST_List2,	
	&asn_DEF_TEST_ListExtensible1,	
	&asn_DEF_TEST_ListExtensible2,	
	&asn_DEF_TEST_List3,	
	&asn_DEF_TEST_Enumerated,	
	&asn_DEF_TEST_TopLevelPDU,	
	0
};

