/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_TEST_UnconstrainedInt_H_
#define	_TEST_UnconstrainedInt_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* TEST-UnconstrainedInt */
typedef struct TEST_UnconstrainedInt {
	long	 attrUciA;
	long	 attrUciB;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TEST_UnconstrainedInt_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TEST_UnconstrainedInt;

#ifdef __cplusplus
}
#endif

#endif	/* _TEST_UnconstrainedInt_H_ */
#include "asn_internal.h"
