/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "TEST-UnconstrainedInt.h"

static asn_TYPE_member_t asn_MBR_TEST_UnconstrainedInt_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TEST_UnconstrainedInt, attrUciA),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attrUciA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TEST_UnconstrainedInt, attrUciB),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attrUciB"
		},
};
static const ber_tlv_tag_t asn_DEF_TEST_UnconstrainedInt_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TEST_UnconstrainedInt_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* attrUciA */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* attrUciB */
};
static asn_SEQUENCE_specifics_t asn_SPC_TEST_UnconstrainedInt_specs_1 = {
	sizeof(struct TEST_UnconstrainedInt),
	offsetof(struct TEST_UnconstrainedInt, _asn_ctx),
	asn_MAP_TEST_UnconstrainedInt_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TEST_UnconstrainedInt = {
	"TEST-UnconstrainedInt",
	"TEST-UnconstrainedInt",
	&asn_OP_SEQUENCE,
	asn_DEF_TEST_UnconstrainedInt_tags_1,
	sizeof(asn_DEF_TEST_UnconstrainedInt_tags_1)
		/sizeof(asn_DEF_TEST_UnconstrainedInt_tags_1[0]), /* 1 */
	asn_DEF_TEST_UnconstrainedInt_tags_1,	/* Same as above */
	sizeof(asn_DEF_TEST_UnconstrainedInt_tags_1)
		/sizeof(asn_DEF_TEST_UnconstrainedInt_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TEST_UnconstrainedInt_1,
	2,	/* Elements count */
	&asn_SPC_TEST_UnconstrainedInt_specs_1	/* Additional specs */
};

