/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "TEST-UnconstrainedReal.h"

static asn_TYPE_member_t asn_MBR_TEST_UnconstrainedReal_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TEST_UnconstrainedReal, attrUcrA),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attrUcrA"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TEST_UnconstrainedReal, attrUcrB),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"attrUcrB"
		},
};
static const ber_tlv_tag_t asn_DEF_TEST_UnconstrainedReal_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TEST_UnconstrainedReal_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* attrUcrA */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* attrUcrB */
};
static asn_SEQUENCE_specifics_t asn_SPC_TEST_UnconstrainedReal_specs_1 = {
	sizeof(struct TEST_UnconstrainedReal),
	offsetof(struct TEST_UnconstrainedReal, _asn_ctx),
	asn_MAP_TEST_UnconstrainedReal_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TEST_UnconstrainedReal = {
	"TEST-UnconstrainedReal",
	"TEST-UnconstrainedReal",
	&asn_OP_SEQUENCE,
	asn_DEF_TEST_UnconstrainedReal_tags_1,
	sizeof(asn_DEF_TEST_UnconstrainedReal_tags_1)
		/sizeof(asn_DEF_TEST_UnconstrainedReal_tags_1[0]), /* 1 */
	asn_DEF_TEST_UnconstrainedReal_tags_1,	/* Same as above */
	sizeof(asn_DEF_TEST_UnconstrainedReal_tags_1)
		/sizeof(asn_DEF_TEST_UnconstrainedReal_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TEST_UnconstrainedReal_1,
	2,	/* Elements count */
	&asn_SPC_TEST_UnconstrainedReal_specs_1	/* Additional specs */
};

