/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_TEST_TopLevelPDU_H_
#define	_TEST_TopLevelPDU_H_


#include "asn_application.h"

/* Including external dependencies */
#include "TEST-UnconstrainedInt.h"
#include "TEST-ConstrainedReal.h"
#include "TEST-NestedChoice.h"
#include "TEST-BitString.h"
#include "TEST-OctetString.h"
#include "TEST-ListExtensible3.h"
#include "TEST-EnumeratedExtensible.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct TEST_ConstrainedReal;
struct TEST_OctetString;

/* TEST-TopLevelPDU */
typedef struct TEST_TopLevelPDU {
	TEST_UnconstrainedInt_t	 opt1;
	TEST_ConstrainedReal_t	*opt2;	/* OPTIONAL */
	TEST_NestedChoice_t	 opt3;
	TEST_BitString_t	 opt4;
	TEST_OctetString_t	*opt5;	/* OPTIONAL */
	TEST_ListExtensible3_t	 opt6;
	TEST_EnumeratedExtensible_t	 opt7;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TEST_TopLevelPDU_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TEST_TopLevelPDU;

#ifdef __cplusplus
}
#endif

#endif	/* _TEST_TopLevelPDU_H_ */
#include "asn_internal.h"
