/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TEST-SM-IEs"
 * 	found in "../v1/test_sm.asn1"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "TEST-NestedChoice.h"

#include "Choice3.h"
#include "ConstrainedChoice3.h"
#include "ConstrainedChoice4.h"
static asn_per_constraints_t asn_PER_type_TEST_NestedChoice_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_TEST_NestedChoice_1[] = {
	{ ATF_POINTER, 0, offsetof(struct TEST_NestedChoice, choice.option1),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_Choice3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"option1"
		},
	{ ATF_POINTER, 0, offsetof(struct TEST_NestedChoice, choice.option2),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ConstrainedChoice3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"option2"
		},
	{ ATF_POINTER, 0, offsetof(struct TEST_NestedChoice, choice.option3),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_ConstrainedChoice4,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"option3"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_TEST_NestedChoice_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* option1 */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* option2 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* option3 */
};
static asn_CHOICE_specifics_t asn_SPC_TEST_NestedChoice_specs_1 = {
	sizeof(struct TEST_NestedChoice),
	offsetof(struct TEST_NestedChoice, _asn_ctx),
	offsetof(struct TEST_NestedChoice, present),
	sizeof(((struct TEST_NestedChoice *)0)->present),
	asn_MAP_TEST_NestedChoice_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_TEST_NestedChoice = {
	"TEST-NestedChoice",
	"TEST-NestedChoice",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_TEST_NestedChoice_constr_1, CHOICE_constraint },
	asn_MBR_TEST_NestedChoice_1,
	3,	/* Elements count */
	&asn_SPC_TEST_NestedChoice_specs_1	/* Additional specs */
};

