/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxnoofKPMNodes_KPMv2 (1024)
#define maxnoofCells_KPMv2 (16384)
#define maxnoofRICStyles_KPMv2 (63)
#define maxnoofMeasurementInfo_KPMv2 (65535)
#define maxnoofLabelInfo_KPMv2 (2147483647)
#define maxnoofMeasurementRecord_KPMv2 (65535)
#define maxnoofMeasurementValue_KPMv2 (2147483647)
#define maxnoofConditionInfo_KPMv2 (32768)
#define maxnoofUEID_KPMv2 (65535)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
