/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "../v2/e2sm_kpm_v2.0.3-rm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_Cell_Measurement_Object_Item_H_
#define	_Cell_Measurement_Object_Item_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CellObjectID.h"
#include "CellGlobalID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Cell-Measurement-Object-Item */
typedef struct Cell_Measurement_Object_Item {
	CellObjectID_t	 cell_object_ID;
	CellGlobalID_t	 cell_global_ID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Cell_Measurement_Object_Item_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Cell_Measurement_Object_Item;
extern asn_SEQUENCE_specifics_t asn_SPC_Cell_Measurement_Object_Item_specs_1;
extern asn_TYPE_member_t asn_MBR_Cell_Measurement_Object_Item_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Cell_Measurement_Object_Item_H_ */
#include "asn_internal.h"
