/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "../v2/e2sm_kpm_v2.0.3-changed.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_E2SM_KPMv2_ActionDefinition_Format3_H_
#define	_E2SM_KPMv2_ActionDefinition_Format3_H_


#include "asn_application.h"

/* Including external dependencies */
#include "CellObjectID-KPMv2.h"
#include "MeasurementCondList-KPMv2.h"
#include "GranularityPeriod-KPMv2.h"
#include "SubscriptionID-KPMv2.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* E2SM-KPMv2-ActionDefinition-Format3 */
typedef struct E2SM_KPMv2_ActionDefinition_Format3 {
	CellObjectID_KPMv2_t	 cellObjID;
	MeasurementCondList_KPMv2_t	 measCondList;
	GranularityPeriod_KPMv2_t	 granulPeriod;
	SubscriptionID_KPMv2_t	 subscriptID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_KPMv2_ActionDefinition_Format3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_KPMv2_ActionDefinition_Format3;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_KPMv2_ActionDefinition_Format3_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_KPMv2_ActionDefinition_Format3_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_KPMv2_ActionDefinition_Format3_H_ */
#include "asn_internal.h"
