/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "../v2/e2sm_kpm_v2.0.2-rm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_GranularityPeriod_H_
#define	_GranularityPeriod_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GranularityPeriod */
typedef long	 GranularityPeriod_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GranularityPeriod;
asn_struct_free_f GranularityPeriod_free;
asn_struct_print_f GranularityPeriod_print;
asn_constr_check_f GranularityPeriod_constraint;
ber_type_decoder_f GranularityPeriod_decode_ber;
der_type_encoder_f GranularityPeriod_encode_der;
xer_type_decoder_f GranularityPeriod_decode_xer;
xer_type_encoder_f GranularityPeriod_encode_xer;
per_type_decoder_f GranularityPeriod_decode_uper;
per_type_encoder_f GranularityPeriod_encode_uper;
per_type_decoder_f GranularityPeriod_decode_aper;
per_type_encoder_f GranularityPeriod_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _GranularityPeriod_H_ */
#include "asn_internal.h"
