/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "../v2/e2sm_kpm_v2.0.3-changed.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_LabelInfoItem_KPMv2_H_
#define	_LabelInfoItem_KPMv2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "MeasurementLabel-KPMv2.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* LabelInfoItem-KPMv2 */
typedef struct LabelInfoItem_KPMv2 {
	MeasurementLabel_KPMv2_t	 measLabel;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LabelInfoItem_KPMv2_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LabelInfoItem_KPMv2;
extern asn_SEQUENCE_specifics_t asn_SPC_LabelInfoItem_KPMv2_specs_1;
extern asn_TYPE_member_t asn_MBR_LabelInfoItem_KPMv2_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _LabelInfoItem_KPMv2_H_ */
#include "asn_internal.h"
