/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "../v2/e2sm_kpm_v2.0.3-rm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "MeasurementRecordItem.h"

asn_per_constraints_t asn_PER_type_MeasurementRecordItem_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_MeasurementRecordItem_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct MeasurementRecordItem, choice.integer),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"integer"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasurementRecordItem, choice.real),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeReal,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"real"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct MeasurementRecordItem, choice.noValue),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"noValue"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_MeasurementRecordItem_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* integer */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* real */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* noValue */
};
asn_CHOICE_specifics_t asn_SPC_MeasurementRecordItem_specs_1 = {
	sizeof(struct MeasurementRecordItem),
	offsetof(struct MeasurementRecordItem, _asn_ctx),
	offsetof(struct MeasurementRecordItem, present),
	sizeof(((struct MeasurementRecordItem *)0)->present),
	asn_MAP_MeasurementRecordItem_tag2el_1,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_MeasurementRecordItem = {
	"MeasurementRecordItem",
	"MeasurementRecordItem",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ 0, &asn_PER_type_MeasurementRecordItem_constr_1, CHOICE_constraint },
	asn_MBR_MeasurementRecordItem_1,
	3,	/* Elements count */
	&asn_SPC_MeasurementRecordItem_specs_1	/* Additional specs */
};

