/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "../v2/e2sm_kpm_v2.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "MeasurementData.h"

#include "MeasurementRecord.h"
asn_per_constraints_t asn_PER_type_MeasurementData_constr_1 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16, -1,  1,  65536 }	/* (SIZE(1..65536)) */,
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_MeasurementData_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_MeasurementRecord,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_MeasurementData_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_MeasurementData_specs_1 = {
	sizeof(struct MeasurementData),
	offsetof(struct MeasurementData, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_MeasurementData = {
	"MeasurementData",
	"MeasurementData",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_MeasurementData_tags_1,
	sizeof(asn_DEF_MeasurementData_tags_1)
		/sizeof(asn_DEF_MeasurementData_tags_1[0]), /* 1 */
	asn_DEF_MeasurementData_tags_1,	/* Same as above */
	sizeof(asn_DEF_MeasurementData_tags_1)
		/sizeof(asn_DEF_MeasurementData_tags_1[0]), /* 1 */
	{ 0, &asn_PER_type_MeasurementData_constr_1, SEQUENCE_OF_constraint },
	asn_MBR_MeasurementData_1,
	1,	/* Single element */
	&asn_SPC_MeasurementData_specs_1	/* Additional specs */
};

