/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-KPM-IEs"
 * 	found in "../v2/e2sm_kpm_v2.0.3-changed.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_QFI_KPMv2_H_
#define	_QFI_KPMv2_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* QFI-KPMv2 */
typedef long	 QFI_KPMv2_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_QFI_KPMv2_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_QFI_KPMv2;
asn_struct_free_f QFI_KPMv2_free;
asn_struct_print_f QFI_KPMv2_print;
asn_constr_check_f QFI_KPMv2_constraint;
ber_type_decoder_f QFI_KPMv2_decode_ber;
der_type_encoder_f QFI_KPMv2_encode_der;
xer_type_decoder_f QFI_KPMv2_decode_xer;
xer_type_encoder_f QFI_KPMv2_encode_xer;
per_type_decoder_f QFI_KPMv2_decode_uper;
per_type_encoder_f QFI_KPMv2_encode_uper;
per_type_decoder_f QFI_KPMv2_decode_aper;
per_type_encoder_f QFI_KPMv2_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _QFI_KPMv2_H_ */
#include "asn_internal.h"
