/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define maxnoofUEs (4294967295)
#define maxnoofSlices (4294967295)
#define maxnoofSlicingNodes (4294967295)
#define maxEARFCN (65535)
#define maxE1APid (65535)
#define maxF1APid (4)
#define maxNRARFCN (3279165)
#define maxnoofNrCellBands (32)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
