/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "E2SM-RSM-ControlHeader.h"

static asn_TYPE_member_t asn_MBR_E2SM_RSM_ControlHeader_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RSM_ControlHeader, rsm_command),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_E2SM_RSM_Command,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rsm-command"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_RSM_ControlHeader_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RSM_ControlHeader_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* rsm-command */
};
static asn_SEQUENCE_specifics_t asn_SPC_E2SM_RSM_ControlHeader_specs_1 = {
	sizeof(struct E2SM_RSM_ControlHeader),
	offsetof(struct E2SM_RSM_ControlHeader, _asn_ctx),
	asn_MAP_E2SM_RSM_ControlHeader_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RSM_ControlHeader = {
	"E2SM-RSM-ControlHeader",
	"E2SM-RSM-ControlHeader",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RSM_ControlHeader_tags_1,
	sizeof(asn_DEF_E2SM_RSM_ControlHeader_tags_1)
		/sizeof(asn_DEF_E2SM_RSM_ControlHeader_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RSM_ControlHeader_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RSM_ControlHeader_tags_1)
		/sizeof(asn_DEF_E2SM_RSM_ControlHeader_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RSM_ControlHeader_1,
	1,	/* Elements count */
	&asn_SPC_E2SM_RSM_ControlHeader_specs_1	/* Additional specs */
};

