/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_E2SM_RSM_IndicationMessage_Format1_H_
#define	_E2SM_RSM_IndicationMessage_Format1_H_


#include "asn_application.h"

/* Including external dependencies */
#include "UE-Identity.h"
#include "CU-UE-F1AP-ID.h"
#include "DU-UE-F1AP-ID.h"
#include "EMMCase.h"
#include "asn_SEQUENCE_OF.h"
#include "constr_SEQUENCE_OF.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct SliceMetrics;

/* E2SM-RSM-IndicationMessage-Format1 */
typedef struct E2SM_RSM_IndicationMessage_Format1 {
	UE_Identity_t	 ueId;
	CU_UE_F1AP_ID_t	 cuUeF1apId;
	DU_UE_F1AP_ID_t	 duUeF1apId;
	EMMCase_t	 emmCase;
	struct E2SM_RSM_IndicationMessage_Format1__ulSlicingMetrics {
		A_SEQUENCE_OF(struct SliceMetrics) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ulSlicingMetrics;
	struct E2SM_RSM_IndicationMessage_Format1__dlSlicingMetrics {
		A_SEQUENCE_OF(struct SliceMetrics) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} dlSlicingMetrics;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RSM_IndicationMessage_Format1_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RSM_IndicationMessage_Format1;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_RSM_IndicationMessage_Format1_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_RSM_IndicationMessage_Format1_1[6];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RSM_IndicationMessage_Format1_H_ */
#include "asn_internal.h"
