/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../v1/ORAN-WG3.E2SM-v02.00.02.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_GlobalNgENB_ID_H_
#define	_GlobalNgENB_ID_H_


#include "asn_application.h"

/* Including external dependencies */
#include "PLMNIdentity.h"
#include "NgENB-ID.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* GlobalNgENB-ID */
typedef struct GlobalNgENB_ID {
	PLMNIdentity_t	 pLMNIdentity;
	NgENB_ID_t	 ngENB_ID;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GlobalNgENB_ID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GlobalNgENB_ID;
extern asn_SEQUENCE_specifics_t asn_SPC_GlobalNgENB_ID_specs_1;
extern asn_TYPE_member_t asn_MBR_GlobalNgENB_ID_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _GlobalNgENB_ID_H_ */
#include "asn_internal.h"
