/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "HARQrextCap.h"

static int
dl_2_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
ul_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_dl_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ul_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	unsigned long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const unsigned long *)sptr;
	
	if((value >= 1)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_dl_constr_2 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (1..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_ul_constr_3 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (1..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_dl_constr_2 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (1..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_ul_constr_3 CC_NOTUSED = {
	{ APC_SEMI_CONSTRAINED,	-1, -1,  1,  0 }	/* (1..MAX) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_dl_specs_2 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_dl_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_dl_2 = {
	"dl",
	"dl",
	&asn_OP_NativeInteger,
	asn_DEF_dl_tags_2,
	sizeof(asn_DEF_dl_tags_2)
		/sizeof(asn_DEF_dl_tags_2[0]) - 1, /* 1 */
	asn_DEF_dl_tags_2,	/* Same as above */
	sizeof(asn_DEF_dl_tags_2)
		/sizeof(asn_DEF_dl_tags_2[0]), /* 2 */
	{ 0, &asn_PER_type_dl_constr_2, dl_2_constraint },
	0, 0,	/* No members */
	&asn_SPC_dl_specs_2	/* Additional specs */
};

static const asn_INTEGER_specifics_t asn_SPC_ul_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_ul_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ul_3 = {
	"ul",
	"ul",
	&asn_OP_NativeInteger,
	asn_DEF_ul_tags_3,
	sizeof(asn_DEF_ul_tags_3)
		/sizeof(asn_DEF_ul_tags_3[0]) - 1, /* 1 */
	asn_DEF_ul_tags_3,	/* Same as above */
	sizeof(asn_DEF_ul_tags_3)
		/sizeof(asn_DEF_ul_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_ul_constr_3, ul_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_ul_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_HARQrextCap_1[] = {
	{ ATF_POINTER, 2, offsetof(struct HARQrextCap, dl),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_dl_2,
		0,
		{ 0, &asn_PER_memb_dl_constr_2,  memb_dl_constraint_1 },
		0, 0, /* No default value */
		"dl"
		},
	{ ATF_POINTER, 1, offsetof(struct HARQrextCap, ul),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_ul_3,
		0,
		{ 0, &asn_PER_memb_ul_constr_3,  memb_ul_constraint_1 },
		0, 0, /* No default value */
		"ul"
		},
};
static const int asn_MAP_HARQrextCap_oms_1[] = { 0, 1 };
static const ber_tlv_tag_t asn_DEF_HARQrextCap_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HARQrextCap_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* dl */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ul */
};
asn_SEQUENCE_specifics_t asn_SPC_HARQrextCap_specs_1 = {
	sizeof(struct HARQrextCap),
	offsetof(struct HARQrextCap, _asn_ctx),
	asn_MAP_HARQrextCap_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_HARQrextCap_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_HARQrextCap = {
	"HARQrextCap",
	"HARQrextCap",
	&asn_OP_SEQUENCE,
	asn_DEF_HARQrextCap_tags_1,
	sizeof(asn_DEF_HARQrextCap_tags_1)
		/sizeof(asn_DEF_HARQrextCap_tags_1[0]), /* 1 */
	asn_DEF_HARQrextCap_tags_1,	/* Same as above */
	sizeof(asn_DEF_HARQrextCap_tags_1)
		/sizeof(asn_DEF_HARQrextCap_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_HARQrextCap_1,
	2,	/* Elements count */
	&asn_SPC_HARQrextCap_specs_1	/* Additional specs */
};

