/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "LinkAdaptation.h"

#include "HARQrextCap.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_cqiCap_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_targetBlerDL_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_targetBlerUL_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_maxMCS_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 28)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_minMCS_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 28)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_riCap_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_type_transmissionMode_constr_12 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_cqiCap_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_targetBlerDL_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_targetBlerUL_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_maxMCS_constr_10 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  28 }	/* (0..28) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_minMCS_constr_11 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 5,  5,  0,  28 }	/* (0..28) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_enum_map_t asn_MAP_riCap_value2enum_3[] = {
	{ 0,	3,	"one" },
	{ 1,	3,	"two" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_riCap_enum2value_3[] = {
	0,	/* one(0) */
	1	/* two(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_riCap_specs_3 = {
	asn_MAP_riCap_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_riCap_enum2value_3,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_riCap_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_riCap_3 = {
	"riCap",
	"riCap",
	&asn_OP_NativeEnumerated,
	asn_DEF_riCap_tags_3,
	sizeof(asn_DEF_riCap_tags_3)
		/sizeof(asn_DEF_riCap_tags_3[0]) - 1, /* 1 */
	asn_DEF_riCap_tags_3,	/* Same as above */
	sizeof(asn_DEF_riCap_tags_3)
		/sizeof(asn_DEF_riCap_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_riCap_constr_3, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_riCap_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_transmissionMode_value2enum_12[] = {
	{ 0,	3,	"one" },
	{ 1,	3,	"two" },
	{ 2,	5,	"three" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_transmissionMode_enum2value_12[] = {
	0,	/* one(0) */
	2,	/* three(2) */
	1	/* two(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_transmissionMode_specs_12 = {
	asn_MAP_transmissionMode_value2enum_12,	/* "tag" => N; sorted by tag */
	asn_MAP_transmissionMode_enum2value_12,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_transmissionMode_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_transmissionMode_12 = {
	"transmissionMode",
	"transmissionMode",
	&asn_OP_NativeEnumerated,
	asn_DEF_transmissionMode_tags_12,
	sizeof(asn_DEF_transmissionMode_tags_12)
		/sizeof(asn_DEF_transmissionMode_tags_12[0]) - 1, /* 1 */
	asn_DEF_transmissionMode_tags_12,	/* Same as above */
	sizeof(asn_DEF_transmissionMode_tags_12)
		/sizeof(asn_DEF_transmissionMode_tags_12[0]), /* 2 */
	{ 0, &asn_PER_type_transmissionMode_constr_12, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_transmissionMode_specs_12	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_LinkAdaptation_1[] = {
	{ ATF_POINTER, 9, offsetof(struct LinkAdaptation, cqiCap),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_cqiCap_constr_2,  memb_cqiCap_constraint_1 },
		0, 0, /* No default value */
		"cqiCap"
		},
	{ ATF_POINTER, 8, offsetof(struct LinkAdaptation, riCap),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_riCap_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"riCap"
		},
	{ ATF_POINTER, 7, offsetof(struct LinkAdaptation, aggregationLevelCap),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_AggregationLevelCap,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"aggregationLevelCap"
		},
	{ ATF_POINTER, 6, offsetof(struct LinkAdaptation, targetBlerDL),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_targetBlerDL_constr_8,  memb_targetBlerDL_constraint_1 },
		0, 0, /* No default value */
		"targetBlerDL"
		},
	{ ATF_POINTER, 5, offsetof(struct LinkAdaptation, targetBlerUL),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_targetBlerUL_constr_9,  memb_targetBlerUL_constraint_1 },
		0, 0, /* No default value */
		"targetBlerUL"
		},
	{ ATF_POINTER, 4, offsetof(struct LinkAdaptation, maxMCS),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_maxMCS_constr_10,  memb_maxMCS_constraint_1 },
		0, 0, /* No default value */
		"maxMCS"
		},
	{ ATF_POINTER, 3, offsetof(struct LinkAdaptation, minMCS),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_minMCS_constr_11,  memb_minMCS_constraint_1 },
		0, 0, /* No default value */
		"minMCS"
		},
	{ ATF_POINTER, 2, offsetof(struct LinkAdaptation, transmissionMode),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_transmissionMode_12,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"transmissionMode"
		},
	{ ATF_POINTER, 1, offsetof(struct LinkAdaptation, harqRetxCap),
		(ASN_TAG_CLASS_CONTEXT | (8 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HARQrextCap,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"harqRetxCap"
		},
};
static const int asn_MAP_LinkAdaptation_oms_1[] = { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
static const ber_tlv_tag_t asn_DEF_LinkAdaptation_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_LinkAdaptation_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* cqiCap */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* riCap */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* aggregationLevelCap */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* targetBlerDL */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* targetBlerUL */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* maxMCS */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* minMCS */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 }, /* transmissionMode */
    { (ASN_TAG_CLASS_CONTEXT | (8 << 2)), 8, 0, 0 } /* harqRetxCap */
};
asn_SEQUENCE_specifics_t asn_SPC_LinkAdaptation_specs_1 = {
	sizeof(struct LinkAdaptation),
	offsetof(struct LinkAdaptation, _asn_ctx),
	asn_MAP_LinkAdaptation_tag2el_1,
	9,	/* Count of tags in the map */
	asn_MAP_LinkAdaptation_oms_1,	/* Optional members */
	9, 0,	/* Root/Additions */
	9,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_LinkAdaptation = {
	"LinkAdaptation",
	"LinkAdaptation",
	&asn_OP_SEQUENCE,
	asn_DEF_LinkAdaptation_tags_1,
	sizeof(asn_DEF_LinkAdaptation_tags_1)
		/sizeof(asn_DEF_LinkAdaptation_tags_1[0]), /* 1 */
	asn_DEF_LinkAdaptation_tags_1,	/* Same as above */
	sizeof(asn_DEF_LinkAdaptation_tags_1)
		/sizeof(asn_DEF_LinkAdaptation_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_LinkAdaptation_1,
	9,	/* Elements count */
	&asn_SPC_LinkAdaptation_specs_1	/* Additional specs */
};

