/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_LinkAdaptation_H_
#define	_LinkAdaptation_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"
#include "NativeEnumerated.h"
#include "AggregationLevelCap.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum LinkAdaptation__riCap {
	LinkAdaptation__riCap_one	= 0,
	LinkAdaptation__riCap_two	= 1
	/*
	 * Enumeration is extensible
	 */
} e_LinkAdaptation__riCap;
typedef enum LinkAdaptation__transmissionMode {
	LinkAdaptation__transmissionMode_one	= 0,
	LinkAdaptation__transmissionMode_two	= 1,
	LinkAdaptation__transmissionMode_three	= 2
	/*
	 * Enumeration is extensible
	 */
} e_LinkAdaptation__transmissionMode;

/* Forward declarations */
struct HARQrextCap;

/* LinkAdaptation */
typedef struct LinkAdaptation {
	long	*cqiCap;	/* OPTIONAL */
	long	*riCap;	/* OPTIONAL */
	AggregationLevelCap_t	*aggregationLevelCap;	/* OPTIONAL */
	long	*targetBlerDL;	/* OPTIONAL */
	long	*targetBlerUL;	/* OPTIONAL */
	long	*maxMCS;	/* OPTIONAL */
	long	*minMCS;	/* OPTIONAL */
	long	*transmissionMode;	/* OPTIONAL */
	struct HARQrextCap	*harqRetxCap;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LinkAdaptation_t;

/* Implementation */
/* extern asn_TYPE_descriptor_t asn_DEF_riCap_3;	// (Use -fall-defs-global to expose) */
/* extern asn_TYPE_descriptor_t asn_DEF_transmissionMode_12;	// (Use -fall-defs-global to expose) */
extern asn_TYPE_descriptor_t asn_DEF_LinkAdaptation;
extern asn_SEQUENCE_specifics_t asn_SPC_LinkAdaptation_specs_1;
extern asn_TYPE_member_t asn_MBR_LinkAdaptation_1[9];

#ifdef __cplusplus
}
#endif

#endif	/* _LinkAdaptation_H_ */
#include "asn_internal.h"
