/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-COMMON-IEs"
 * 	found in "../v1/ORAN-WG3.E2SM-v02.00.02.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_NR_PCI_H_
#define	_NR_PCI_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* NR-PCI */
typedef long	 NR_PCI_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_NR_PCI_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_NR_PCI;
asn_struct_free_f NR_PCI_free;
asn_struct_print_f NR_PCI_print;
asn_constr_check_f NR_PCI_constraint;
ber_type_decoder_f NR_PCI_decode_ber;
der_type_encoder_f NR_PCI_encode_der;
xer_type_decoder_f NR_PCI_decode_xer;
xer_type_encoder_f NR_PCI_encode_xer;
per_type_decoder_f NR_PCI_decode_uper;
per_type_encoder_f NR_PCI_encode_uper;
per_type_decoder_f NR_PCI_decode_aper;
per_type_encoder_f NR_PCI_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _NR_PCI_H_ */
#include "asn_internal.h"
