/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_RSM_Trigger_Type_H_
#define	_RSM_Trigger_Type_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeEnumerated.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum RSM_Trigger_Type {
	RSM_Trigger_Type_upon_emm_case_report	= 0,
	RSM_Trigger_Type_periodic	= 1
	/*
	 * Enumeration is extensible
	 */
} e_RSM_Trigger_Type;

/* RSM-Trigger-Type */
typedef long	 RSM_Trigger_Type_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_RSM_Trigger_Type_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_RSM_Trigger_Type;
extern const asn_INTEGER_specifics_t asn_SPC_RSM_Trigger_Type_specs_1;
asn_struct_free_f RSM_Trigger_Type_free;
asn_struct_print_f RSM_Trigger_Type_print;
asn_constr_check_f RSM_Trigger_Type_constraint;
ber_type_decoder_f RSM_Trigger_Type_decode_ber;
der_type_encoder_f RSM_Trigger_Type_encode_der;
xer_type_decoder_f RSM_Trigger_Type_decode_xer;
xer_type_encoder_f RSM_Trigger_Type_encode_xer;
per_type_decoder_f RSM_Trigger_Type_decode_uper;
per_type_encoder_f RSM_Trigger_Type_encode_uper;
per_type_decoder_f RSM_Trigger_Type_decode_aper;
per_type_encoder_f RSM_Trigger_Type_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _RSM_Trigger_Type_H_ */
#include "asn_internal.h"
