/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_SliceIDAssoc_H_
#define	_SliceIDAssoc_H_


#include "asn_application.h"

/* Including external dependencies */
#include "NativeInteger.h"

#ifdef __cplusplus
extern "C" {
#endif

/* SliceIDAssoc */
typedef unsigned long	 SliceIDAssoc_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SliceIDAssoc_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SliceIDAssoc;
extern const asn_INTEGER_specifics_t asn_SPC_SliceIDAssoc_specs_1;
asn_struct_free_f SliceIDAssoc_free;
asn_struct_print_f SliceIDAssoc_print;
asn_constr_check_f SliceIDAssoc_constraint;
ber_type_decoder_f SliceIDAssoc_decode_ber;
der_type_encoder_f SliceIDAssoc_encode_der;
xer_type_decoder_f SliceIDAssoc_decode_xer;
xer_type_encoder_f SliceIDAssoc_encode_xer;
per_type_decoder_f SliceIDAssoc_decode_uper;
per_type_encoder_f SliceIDAssoc_encode_uper;
per_type_decoder_f SliceIDAssoc_decode_aper;
per_type_encoder_f SliceIDAssoc_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SliceIDAssoc_H_ */
#include "asn_internal.h"
