/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#include "SliceMetrics.h"

static int
numUeAssocToSlice_3_constraint(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

/*
 * This type is implemented using NativeInteger,
 * so here we adjust the DEF accordingly.
 */
static int
memb_prbUtilization_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_numUeAssocToSlice_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	
	/* Constraint check succeeded */
	return 0;
}

static int
memb_sliceLevelBLER_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 100)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_avgCQI_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 15)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_per_constraints_t asn_PER_type_numUeAssocToSlice_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_prbUtilization_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_numUeAssocToSlice_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1,  0,  4294967295 }	/* (0..4294967295) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_sliceLevelBLER_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 7,  7,  0,  100 }	/* (0..100) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_per_constraints_t asn_PER_memb_avgCQI_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 4,  4,  0,  15 }	/* (0..15) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static const asn_INTEGER_specifics_t asn_SPC_numUeAssocToSlice_specs_3 = {
	0,	0,	0,	0,	0,
	0,	/* Native long size */
	1	/* Unsigned representation */
};
static const ber_tlv_tag_t asn_DEF_numUeAssocToSlice_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (2 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_numUeAssocToSlice_3 = {
	"numUeAssocToSlice",
	"numUeAssocToSlice",
	&asn_OP_NativeInteger,
	asn_DEF_numUeAssocToSlice_tags_3,
	sizeof(asn_DEF_numUeAssocToSlice_tags_3)
		/sizeof(asn_DEF_numUeAssocToSlice_tags_3[0]) - 1, /* 1 */
	asn_DEF_numUeAssocToSlice_tags_3,	/* Same as above */
	sizeof(asn_DEF_numUeAssocToSlice_tags_3)
		/sizeof(asn_DEF_numUeAssocToSlice_tags_3[0]), /* 2 */
	{ 0, &asn_PER_type_numUeAssocToSlice_constr_3, numUeAssocToSlice_3_constraint },
	0, 0,	/* No members */
	&asn_SPC_numUeAssocToSlice_specs_3	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_SliceMetrics_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct SliceMetrics, prbUtilization),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_prbUtilization_constr_2,  memb_prbUtilization_constraint_1 },
		0, 0, /* No default value */
		"prbUtilization"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SliceMetrics, numUeAssocToSlice),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_numUeAssocToSlice_3,
		0,
		{ 0, &asn_PER_memb_numUeAssocToSlice_constr_3,  memb_numUeAssocToSlice_constraint_1 },
		0, 0, /* No default value */
		"numUeAssocToSlice"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SliceMetrics, sliceLevelBLER),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_sliceLevelBLER_constr_4,  memb_sliceLevelBLER_constraint_1 },
		0, 0, /* No default value */
		"sliceLevelBLER"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct SliceMetrics, avgCQI),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ 0, &asn_PER_memb_avgCQI_constr_5,  memb_avgCQI_constraint_1 },
		0, 0, /* No default value */
		"avgCQI"
		},
};
static const ber_tlv_tag_t asn_DEF_SliceMetrics_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_SliceMetrics_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* prbUtilization */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* numUeAssocToSlice */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* sliceLevelBLER */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* avgCQI */
};
asn_SEQUENCE_specifics_t asn_SPC_SliceMetrics_specs_1 = {
	sizeof(struct SliceMetrics),
	offsetof(struct SliceMetrics, _asn_ctx),
	asn_MAP_SliceMetrics_tag2el_1,
	4,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_SliceMetrics = {
	"SliceMetrics",
	"SliceMetrics",
	&asn_OP_SEQUENCE,
	asn_DEF_SliceMetrics_tags_1,
	sizeof(asn_DEF_SliceMetrics_tags_1)
		/sizeof(asn_DEF_SliceMetrics_tags_1[0]), /* 1 */
	asn_DEF_SliceMetrics_tags_1,	/* Same as above */
	sizeof(asn_DEF_SliceMetrics_tags_1)
		/sizeof(asn_DEF_SliceMetrics_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_SliceMetrics_1,
	4,	/* Elements count */
	&asn_SPC_SliceMetrics_specs_1	/* Additional specs */
};

