/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RSM-IEs"
 * 	found in "../v1/e2sm-rsm.asn"
 * 	`asn1c -fcompound-names -fincludes-quoted -fno-include-deps -findirect-choice -gen-PER -no-gen-OER -D.`
 */

#ifndef	_SliceParameters_H_
#define	_SliceParameters_H_


#include "asn_application.h"

/* Including external dependencies */
#include "SchedulerType.h"
#include "NativeInteger.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct ScheduleConfig;

/* SliceParameters */
typedef struct SliceParameters {
	SchedulerType_t	 schedulerType;
	long	*weight;	/* OPTIONAL */
	long	*qosLevel;	/* OPTIONAL */
	struct ScheduleConfig	*scheduleInfo;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SliceParameters_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SliceParameters;
extern asn_SEQUENCE_specifics_t asn_SPC_SliceParameters_specs_1;
extern asn_TYPE_member_t asn_MBR_SliceParameters_1[4];

#ifdef __cplusplus
}
#endif

#endif	/* _SliceParameters_H_ */
#include "asn_internal.h"
