# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: e2sm_mho/v1/e2sm_mho.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto
from betterproto.grpc.grpclib_server import ServiceBase


class MhoTriggerType(betterproto.Enum):
    """enumerated from e2sm-mho.asn1:64{MHO-Trigger-Type}"""

    MHO_TRIGGER_TYPE_PERIODIC = 0
    MHO_TRIGGER_TYPE_UPON_RCV_MEAS_REPORT = 1
    MHO_TRIGGER_TYPE_UPON_CHANGE_RRC_STATUS = 2


class Rrcstatus(betterproto.Enum):
    """enumerated from e2sm-mho.asn1:134{RRCStatus}"""

    RRCSTATUS_CONNECTED = 0
    RRCSTATUS_INACTIVE = 1
    RRCSTATUS_IDLE = 2


class MhoCommand(betterproto.Enum):
    """enumerated from e2sm-mho.asn1:154{MHO-Command}"""

    MHO_COMMAND_INITIATE_HANDOVER = 0


@dataclass(eq=False, repr=False)
class Eutracgi(betterproto.Message):
    """sequence from e2sm-mho.asn1:21 {EUTRACGI}"""

    p_lmn_identity: "PlmnIdentity" = betterproto.message_field(1)
    e_utracell_identity: "EutracellIdentity" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class Nrcgi(betterproto.Message):
    """sequence from e2sm-mho.asn1:27 {NRCGI}"""

    p_lmn_identity: "PlmnIdentity" = betterproto.message_field(1)
    n_rcell_identity: "NrcellIdentity" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class CellGlobalId(betterproto.Message):
    """sequence from e2sm-mho.asn1:33{CellGlobalID}"""

    nr_cgi: "Nrcgi" = betterproto.message_field(1, group="cell_global_id")
    e_utra_cgi: "Eutracgi" = betterproto.message_field(2, group="cell_global_id")


@dataclass(eq=False, repr=False)
class Rsrp(betterproto.Message):
    """range of Integer from e2sm-mho.asn1:40 {RSRP}"""

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class MaxofMessageProtocolTests(betterproto.Message):
    """constant Integer from e2sm-mho.asn1:48{-}"""

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class MaxofRicstyles(betterproto.Message):
    """constant Integer from e2sm-mho.asn1:49{-}"""

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class MaxPlmn(betterproto.Message):
    """constant Integer from e2sm-mho.asn1:50{-}"""

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class MaxNr(betterproto.Message):
    """constant Integer from e2sm-mho.asn1:51{-}"""

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class RicStyleType(betterproto.Message):
    """range of Integer from e2sm-mho.asn1:55 {RIC-Style-Type}"""

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class RicFormatType(betterproto.Message):
    """range of Integer from e2sm-mho.asn1:61{RIC-Format-Type}"""

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class RicControlMessagePriority(betterproto.Message):
    """
    range of Integer from e2sm-mho.asn1:63 {RIC-Control-Message-Priority}
    """

    value: int = betterproto.int32_field(1)


@dataclass(eq=False, repr=False)
class E2SmMhoEventTriggerDefinition(betterproto.Message):
    """sequence from e2sm-mho.asn1:79 {E2SM-MHO-EventTriggerDefinition}"""

    event_definition_format1: "E2SmMhoEventTriggerDefinitionFormat1" = (
        betterproto.message_field(1, group="e2_sm_mho_event_trigger_definition")
    )


@dataclass(eq=False, repr=False)
class E2SmMhoEventTriggerDefinitionFormat1(betterproto.Message):
    """
    sequence from e2sm-mho.asn1:84 {E2SM-MHO-EventTriggerDefinition-Format1}
    """

    trigger_type: "MhoTriggerType" = betterproto.enum_field(1)
    reporting_period_ms: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class E2SmMhoIndicationHeader(betterproto.Message):
    """sequence from e2sm-mho.asn1:95 {E2SM-MHO-IndicationHeader}"""

    indication_header_format1: "E2SmMhoIndicationHeaderFormat1" = (
        betterproto.message_field(1, group="e2_sm_mho_indication_header")
    )


@dataclass(eq=False, repr=False)
class E2SmMhoIndicationHeaderFormat1(betterproto.Message):
    """sequence from e2sm-mho.asn1:101 {E2SM-MHO-IndicationHeader-Format1}"""

    cgi: "CellGlobalId" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class E2SmMhoIndicationMessage(betterproto.Message):
    """sequence from e2sm-mho.asn1:111 {E2SM-MHO-IndicationMessage}"""

    indication_message_format1: "E2SmMhoIndicationMessageFormat1" = (
        betterproto.message_field(1, group="e2_sm_mho_indication_message")
    )
    indication_message_format2: "E2SmMhoIndicationMessageFormat2" = (
        betterproto.message_field(2, group="e2_sm_mho_indication_message")
    )


@dataclass(eq=False, repr=False)
class E2SmMhoIndicationMessageFormat1(betterproto.Message):
    """sequence from e2sm-mho.asn1:121 {E2SM-MHO-IndicationMessage-Format1}"""

    ue_id: "UeIdentity" = betterproto.message_field(1)
    meas_report: List["E2SmMhoMeasurementReportItem"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class E2SmMhoMeasurementReportItem(betterproto.Message):
    """sequence from e2sm-mho.asn1:128 {E2SM-MHO-MeasurementReportItem}"""

    cgi: "CellGlobalId" = betterproto.message_field(1)
    rsrp: "Rsrp" = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class E2SmMhoIndicationMessageFormat2(betterproto.Message):
    """sequence from e2sm-mho.asn1:129 {E2SM-MHO-IndicationMessage-Format2}"""

    ue_id: "UeIdentity" = betterproto.message_field(1)
    rrc_status: "Rrcstatus" = betterproto.enum_field(2)


@dataclass(eq=False, repr=False)
class E2SmMhoControlHeader(betterproto.Message):
    """sequence from e2sm-mho.asn1:143 {E2SM-MHO-ControlHeader}"""

    control_header_format1: "E2SmMhoControlHeaderFormat1" = betterproto.message_field(
        1, group="e2_sm_mho_control_header"
    )


@dataclass(eq=False, repr=False)
class E2SmMhoControlHeaderFormat1(betterproto.Message):
    """sequence from e2sm-mho.asn1:149 {E2SM-MHO-ControlHeader-Format1}"""

    rc_command: "MhoCommand" = betterproto.enum_field(1)
    ric_control_message_priority: "RicControlMessagePriority" = (
        betterproto.message_field(2)
    )


@dataclass(eq=False, repr=False)
class E2SmMhoControlMessage(betterproto.Message):
    """sequence from e2sm-mho.asn1:163 {E2SM-MHO-ControlMessage}"""

    control_message_format1: "E2SmMhoControlMessageFormat1" = betterproto.message_field(
        1, group="e2_sm_mho_control_message"
    )


@dataclass(eq=False, repr=False)
class E2SmMhoControlMessageFormat1(betterproto.Message):
    """sequence from e2sm-mho.asn1:169 {E2SM-MHO-ControlMessage-Format1}"""

    serving_cgi: "CellGlobalId" = betterproto.message_field(1)
    ued_id: "UeIdentity" = betterproto.message_field(2)
    target_cgi: "CellGlobalId" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class E2SmMhoRanfunctionDescription(betterproto.Message):
    """sequence from e2sm-mho.asn1:181 {E2SM-MHO-RANfunction-Description}"""

    ran_function_name: "RanfunctionName" = betterproto.message_field(1)
    ric_event_trigger_style_list: List[
        "RicEventTriggerStyleList"
    ] = betterproto.message_field(2)
    ric_report_style_list: List["RicReportStyleList"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class RanfunctionName(betterproto.Message):
    """sequence from e2sm-mho.asn1:191 {RANfunction-Name}"""

    ran_function_short_name: str = betterproto.string_field(1)
    ran_function_e2_sm_oid: str = betterproto.string_field(2)
    ran_function_description: str = betterproto.string_field(3)
    ran_function_instance: int = betterproto.int32_field(4)


@dataclass(eq=False, repr=False)
class RicEventTriggerStyleList(betterproto.Message):
    """sequence from e2sm-mho.asn1:199 {RIC-EventTriggerStyle-List}"""

    ric_event_trigger_style_type: "RicStyleType" = betterproto.message_field(1)
    ric_event_trigger_style_name: "RicStyleName" = betterproto.message_field(2)
    ric_event_trigger_format_type: "RicFormatType" = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class RicReportStyleList(betterproto.Message):
    """sequence from e2sm-mho.asn1:206 {RIC-ReportStyle-List}"""

    ric_report_style_type: "RicStyleType" = betterproto.message_field(1)
    ric_report_style_name: "RicStyleName" = betterproto.message_field(2)
    ric_indication_header_format_type: "RicFormatType" = betterproto.message_field(3)
    ric_indication_message_format_type: "RicFormatType" = betterproto.message_field(4)


@dataclass(eq=False, repr=False)
class RicStyleName(betterproto.Message):
    """{RIC-Style-Name}"""

    value: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class UeIdentity(betterproto.Message):
    """{UE-Identity}"""

    value: str = betterproto.string_field(1)


@dataclass(eq=False, repr=False)
class PlmnIdentity(betterproto.Message):
    """{PLMN-Identity}"""

    value: bytes = betterproto.bytes_field(1)


@dataclass(eq=False, repr=False)
class EutracellIdentity(betterproto.Message):
    """{EUTRACellIdentity}"""

    value: "BitString" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class NrcellIdentity(betterproto.Message):
    """{NRCellIdentity}"""

    value: "BitString" = betterproto.message_field(1)


@dataclass(eq=False, repr=False)
class BitString(betterproto.Message):
    """{BIT_STRING}"""

    value: int = betterproto.uint64_field(1)
    len: int = betterproto.uint32_field(2)
