# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: Test integration
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:
  buflint:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v4
     - name: buflint
       env:
         BUF_VERSION: 1.0.0
       run: |
         cd ..
         sudo git clone https://github.com/onosproject/onos-lib-go.git
         cd onos-e2-sm
         docker run \
           -v `pwd`:/go/src/github.com/onosproject/onos-e2-sm \
           -v `pwd`/../onos-lib-go/api/asn1:/go/src/github.com/onosproject/onos-e2-sm/servicemodels/asn1 \
           -w /go/src/github.com/onosproject/onos-e2-sm/servicemodels \
             bufbuild/buf:${BUF_VERSION} lint