# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: Docker
on:
  push:
    branches:
      - master
  pull_request:

env:
  E2T_MOD: github.com/onosproject/onos-e2t@master
  ONOS_E2_SM_VERSION: latest

jobs:
  docker-e2sm_kpm_v2_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-build
        run: |
          ./build/bin/build-deps e2sm_kpm_v2_go $E2T_MOD onosproject/service-model-docker-e2sm_kpm_v2_go-1.0.0:latest
          docker build . -f build/plugins/Dockerfile \
          --build-arg PLUGIN_MAKE_TARGET="e2sm_kpm_v2_go" \
          --build-arg PLUGIN_MAKE_VERSION="1.0.0" \
          -t onosproject/service-model-docker-e2sm_kpm_v2_go-1.0.0:$ONOS_E2_SM_VERSION

  docker-e2sm_rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-build
        run: |
          ./build/bin/build-deps e2sm_rc $E2T_MOD onosproject/service-model-docker-e2sm_rc-1.0.0:latest
          docker build . -f build/plugins/Dockerfile \
          --build-arg PLUGIN_MAKE_TARGET="e2sm_rc" \
          --build-arg PLUGIN_MAKE_VERSION="1.0.0" \
          -t onosproject/service-model-docker-e2sm_rc-1.0.0:$ONOS_E2_SM_VERSION

  docker-e2sm_rc_pre_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-build
        run: |
          ./build/bin/build-deps e2sm_rc_pre_go $E2T_MOD onosproject/service-model-docker-e2sm_rc_pre_go-1.0.0:latest
          docker build . -f build/plugins/Dockerfile \
          --build-arg PLUGIN_MAKE_TARGET="e2sm_rc_pre_go" \
          --build-arg PLUGIN_MAKE_VERSION="1.0.0" \
          -t onosproject/service-model-docker-e2sm_rc_pre_go-1.0.0:$ONOS_E2_SM_VERSION

  docker-e2sm_mho_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-build
        run: |
          ./build/bin/build-deps e2sm_mho_go $E2T_MOD onosproject/service-model-docker-e2sm_mho_go-1.0.0:latest
          docker build . -f build/plugins/Dockerfile \
          --build-arg PLUGIN_MAKE_TARGET="e2sm_mho_go" \
          --build-arg PLUGIN_MAKE_VERSION="1.0.0" \
          -t onosproject/service-model-docker-e2sm_mho_go-1.0.0:$ONOS_E2_SM_VERSION

  docker-e2sm_rsm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: docker-build
        run: |
          ./build/bin/build-deps e2sm_rsm $E2T_MOD onosproject/service-model-docker-e2sm_rsm-1.0.0:latest
          docker build . -f build/plugins/Dockerfile \
          --build-arg PLUGIN_MAKE_TARGET="e2sm_rsm" \
          --build-arg PLUGIN_MAKE_VERSION="1.0.0" \
          -t onosproject/service-model-docker-e2sm_rsm-1.0.0:$ONOS_E2_SM_VERSION
