# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Build
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:
  e2sm_rsm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: |
          cd servicemodels/e2sm_rsm
          go build -o build/_output/e2sm_rsm.so.1.0.0 -buildmode=plugin .

      - name: lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: -v --config ./.golangci.yml --timeout=15m

      - name: Unit tests
        run: cd servicemodels/e2sm_rsm && go test -race ./...

      - name: docker-build
        run: |
          ./build/bin/build-deps e2sm_rsm $E2T_MOD onosproject/service-model-docker-e2sm_rsm-1.0.0:$ONOS_E2_SM_VERSION
          docker build . -f build/plugins/Dockerfile \
          --build-arg PLUGIN_MAKE_TARGET="e2sm_rsm" \
          --build-arg PLUGIN_MAKE_VERSION="1.0.0" \
          -t onosproject/service-model-docker-e2sm_rsm-1.0.0:$ONOS_E2_SM_VERSION

      - name: reuse lint
        uses: fsfe/reuse-action@v3

      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 6d304c09a3ec097ba4517724e4a4d17d
