# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: e2sm_kpm_v2
on:
  push:
    branches:
      - master
  pull_request:

env:
  E2T_MOD: github.com/onosproject/onos-e2t@master
  ONOS_E2_SM_VERSION: latest

jobs:
  e2sm_kpm_v2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_kpm_v2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: go build -o build/_output/e2sm_kpm_v2.so.1.0.0 -buildmode=plugin .

      - name: Unit tests
        run: GODEBUG=cgocheck=0 go test -race ./...

      - name: docker-build
        run: |
          cd ../..
          ./build/bin/build-deps e2sm_kpm_v2 $E2T_MOD onosproject/service-model-docker-e2sm_kpm_v2-1.0.0:$ONOS_E2_SM_VERSION
          docker build . -f build/plugins/Dockerfile \
          --build-arg PLUGIN_MAKE_TARGET="e2sm_kpm_v2" \
          --build-arg PLUGIN_MAKE_VERSION="1.0.0" \
          -t onosproject/service-model-docker-e2sm_kpm_v2-1.0.0:$ONOS_E2_SM_VERSION

