# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: License-Fossa-check
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: reuse lint
        uses: fsfe/reuse-action@v2

  fossa-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 9dc8fa92e3dd565687317beb87b56d89
