# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: Linters
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  buflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: buflint
        env:
          BUF_VERSION: 1.0.0
        run: |
          cd ..
          git clone https://github.com/onosproject/onos-lib-go.git
          cd onos-e2-sm
          docker run \
            -v `pwd`:/go/src/github.com/onosproject/onos-e2-sm \
            -v `pwd`/../onos-lib-go/api/asn1:/go/src/github.com/onosproject/onos-e2-sm/servicemodels/asn1 \
            -w /go/src/github.com/onosproject/onos-e2-sm/servicemodels \
            bufbuild/buf:$BUF_VERSION lint

  sm-linters-e2sm_kpm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_kpm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_kpm_v2:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_kpm_v2
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_kpm_v2_go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_kpm_v2_go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_rc:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_rc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_rc_pre:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_rc_pre
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_rc_pre_go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_rc_pre_go
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_mho:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_mho
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_ni:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_ni
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-e2sm_rsm:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/e2sm_rsm
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-test_sm_aper_go_lib:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./servicemodels/test_sm_aper_go_lib
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-protoc-gen-cgo:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protoc-gen-cgo
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-protoc-gen-choice:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protoc-gen-choice
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml

  sm-linters-protoc-gen-builder:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./protoc-gen-builder
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - uses: golangci/golangci-lint-action@v3.7.0
        with:
          version: latest
          args: -v --config ./.golangci.yml
