# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: Master
on:
  push:
    branches:
      - master
      - Githubactions
  pull_request:

env:
  ONOS_PROTOC_VERSION: v1.0.2
  BUF_VERSION: 1.0.0

jobs:
  master:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: protos
        run: |
          cd ..
          sudo git clone https://github.com/onosproject/onos-lib-go.git
          cd onos-e2-sm
          docker run \
            -v `pwd`:/go/src/github.com/onosproject/onos-e2-sm \
            -v `pwd`/../onos-lib-go:/go/src/github.com/onosproject/onos-lib-go \
            -w /go/src/github.com/onosproject/onos-e2-sm \
            --entrypoint /go/src/github.com/onosproject/onos-e2-sm/build/bin/compile-protos.sh \
            onosproject/protoc-go:$ONOS_PROTOC_VERSION

      - name: protos-py
        run: |
          docker run \
            -v `pwd`:/go/src/github.com/onosproject/onos-e2-sm \
            -v `pwd`/../onos-lib-go:/go/src/github.com/onosproject/onos-lib-go \
            -w /go/src/github.com/onosproject/onos-e2-sm \
            --entrypoint /go/src/github.com/onosproject/onos-e2-sm/build/bin/compile-protos-py.sh \
            onosproject/protoc-go:$ONOS_PROTOC_VERSION

      - name: buflint
        run: |
          docker run \
            -v `pwd`:/go/src/github.com/onosproject/onos-e2-sm \
            -v `pwd`/../onos-lib-go/api/asn1:/go/src/github.com/onosproject/onos-e2-sm/servicemodels/asn1 \
            -w /go/src/github.com/onosproject/onos-e2-sm/servicemodels \
            bufbuild/buf:$BUF_VERSION lint

      - name: lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: -v --config ./.golangci.yml --timeout=15m

      - name: reuse lint
        uses: fsfe/reuse-action@v3

      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 6d304c09a3ec097ba4517724e4a4d17d

