# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation

name: Build
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:
  protoc_gen_choice:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Build
        run: |
          cd protoc_gen_choice/
          go build -v -o ./protoc_gen_choice

      - name: lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: -v --config ./.golangci.yml --timeout=15m

      - name: Unit tests
        run: cd protoc_gen_choice/ && go test -race ./...

      - name: reuse lint
        uses: fsfe/reuse-action@v3

      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 6d304c09a3ec097ba4517724e4a4d17d
