# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Intel Corporation
name: Test integration
on:
  push:
    branches:
      - master
      - GHA-integration
  pull_request:

jobs:
  unit-tests-e2sm_rc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_rc && go test -race ./...

  unit-tests-e2sm_kpm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_kpm && GODEBUG=cgocheck=0 go test -race ./...

  unit-tests-e2sm_rc_pre:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_rc_pre && GODEBUG=cgocheck=0 go test -race ./...

  unit-tests-e2sm_rc_pre_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_rc_pre_go && go test -race ./...

  unit-tests-e2sm_kpm_v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_kpm_v2 && GODEBUG=cgocheck=0 go test -race ./...

  unit-tests-e2sm_kpm_v2_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_kpm_v2_go && go test -race ./...

  unit-tests-e2sm_mho:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_mho && GODEBUG=cgocheck=0 go test -race ./...

  unit-tests-e2sm_mho_go:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_mho_go && go test -race ./...

  unit-tests-e2sm_rsm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/e2sm_rsm && go test -race ./...

  unit-tests-test_sm_aper_go_lib:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v3
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
      - name: Unit tests
        run: |
          cd servicemodels/test_sm_aper_go_lib/testsmctypes && GODEBUG=cgocheck=0 go test -race ./...